### PR TITLE
bucketsample: locking isnt necessary due to atomics

### PR DESCRIPTION
**Pull request by zklapow**
@jschlather @jhaber

### CODE REVIEW

**Comment by jhaber** [comment]
Presumably the atomics will make it not blow up, but is it still possible to still see inconsistent data if reading/writing concurrently?

**Comment by zklapow** [comment]
ya the downside to this is like the sum/count could be mismatched with the bucket data... I think thats an ok tradeoff?

**Comment by jhaber** [comment]
I was mostly just being pessimistic without looking at the code (theoretically we could be splitting or resizing buckets in the write path, and concurrent reads could run into issues). However it seems like we're just lazily initializing the long arrays, so this seems fine to me

**Comment by zklapow** [comment]
ya I think b/c its just the lazy init and even that is done as a `compareAndSet` on an atomic we should be safe.

**Pull request merged**
